# Generated by Django 4.1.2 on 2022-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
