# Generated by Django 4.1.2 on 2022-11-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
