# Generated by Django 4.1.2 on 2022-11-04 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
