# Generated by Django 4.1.2 on 2022-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fantastic_discount',
            field=models.BooleanField(default=False),
        ),
    ]
