# Generated by Django 4.1.2 on 2022-11-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_discount_order_subtotal_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
